### PR TITLE
How I can find the module for direct debit ?

### PR DESCRIPTION
**Pull request by RBrezel**
Hello.
I had installed the mollie on Gambio. But i can'd finde the module for direct debit.
The module mollie_directdebit.php is upsend, or not programmed. Is n't it?
thx
Ralf

### CODE REVIEW

**Comment by DamjanLogeecom** [comment]
Hello Ralf,

Please note that we have received your question and we will notify you once we have more information to provide.

Kind regards.

**Comment by DamjanLogeecom** [comment]
Hello again Ralf,

We would like to kindly request further clarification regarding the issue you are experiencing. Are you encountering any problems with displaying the payment method during checkout, or is the payment method missing from the plugin page?

To help us better understand the issue, it would be greatly appreciated if you could provide us with some screenshots or steps to reproduce the problem.

Thank you,

Best regards.

**Comment by RBrezel** [comment]
Hello DamjanLogeecom.
Bildschirmfoto vom 2023-03-16 11-46-27
In the Mollie Configuration you can see downline to install SEPA Direct Debit - an you can see the link.
But it will not install, because theapp is not available.

**Comment by DamjanLogeecom** [comment]
Hello Ralf,

Please note that our team is reviewing your request and has already started working on resolving your issue.

If you have any questions or concerns, please let us know.

Kind regards.

**Comment by tanjalog** [comment]
Hey @RBrezel ,

Please note that our team is working on this issue and be sure that we will update you as soon as possible.

Best regards

**Comment by tanjalog** [comment]
Hey @RBrezel

First, thanks for reaching out to us.

Please note that our team investigate your request and we want to inform you that the SEPA Direct Debit payment method is not currently supported in the Gambio integration.

 It will be added at some point in the future (we can not give you precise information at this moment).

Best regards.

**Comment by Pixopax** [comment]
Hello,

 

you have the wrong one, I asked about the compatibility of the Mollie plugin with Gambio 4.8.0.0

 

 

Mit freundlichen Grüßen,

 

Rocketronics.de

Dipl. -Ing (FH) Louis Schreyer

Hugo-Grotius-Straße 18

27404 Zeven

GERMANY

 

Tel: 04281 5079782 Mo-Fr. 14:00-18:00

Email:  ***@***.***> ***@***.***

Shop:  <http://www.rocketronics.de/> www.rocketronics.de

 



 

USt.-IdNr: DE813546414
WEEE-Reg.-Nr. DE 35691149

Rocketronics.de ist ein Einzelunternehmen

Der Inhaber ist Dipl. -Ing (FH) Louis Schreyer

 

Von: tanjalog ***@***.***> 
Gesendet: Freitag, 7. April 2023 11:23
An: mollie/gambio ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [mollie/gambio] How I can find the module for direct debit ? (PR #82)

 

Hey @RBrezel <https://github.com/RBrezel> 

First, thanks for reaching out to us.

Please note that our team investigate your request and we want to inform you that the SEPA Direct Debit payment method is not currently supported in the Gambio integration.

It will be added at some point in the future (we can not give you precise information at this moment).

Best regards.

**Comment by RBrezel** [comment]
At first. THX for all.

My using Version of Gambio is v4.6.0.2

@tanjalog - All Ok. if it will be ready in the next some month. :-)

**Pull request closed without merging**
